//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_1.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Action_Tree_Data = new HashSet<Action_Tree_Data>();
            this.Action_Tree_Data1 = new HashSet<Action_Tree_Data>();
            this.Action_Tree_Data2 = new HashSet<Action_Tree_Data>();
            this.Action_Tree_Data3 = new HashSet<Action_Tree_Data>();
            this.Category1 = new HashSet<Category>();
            this.ReportedIssue_Tree_Data = new HashSet<ReportedIssue_Tree_Data>();
            this.ReportedIssue_Tree_Data1 = new HashSet<ReportedIssue_Tree_Data>();
            this.ReportedIssue_Tree_Data2 = new HashSet<ReportedIssue_Tree_Data>();
            this.ReportedIssue_Tree_Data3 = new HashSet<ReportedIssue_Tree_Data>();
            this.RootCause_Tree_Data = new HashSet<RootCause_Tree_Data>();
            this.RootCause_Tree_Data1 = new HashSet<RootCause_Tree_Data>();
            this.RootCause_Tree_Data2 = new HashSet<RootCause_Tree_Data>();
            this.RootCause_Tree_Data3 = new HashSet<RootCause_Tree_Data>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public int ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Tree_Data> Action_Tree_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Tree_Data> Action_Tree_Data1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Tree_Data> Action_Tree_Data2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Tree_Data> Action_Tree_Data3 { get; set; }
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedIssue_Tree_Data> ReportedIssue_Tree_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedIssue_Tree_Data> ReportedIssue_Tree_Data1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedIssue_Tree_Data> ReportedIssue_Tree_Data2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportedIssue_Tree_Data> ReportedIssue_Tree_Data3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootCause_Tree_Data> RootCause_Tree_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootCause_Tree_Data> RootCause_Tree_Data1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootCause_Tree_Data> RootCause_Tree_Data2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RootCause_Tree_Data> RootCause_Tree_Data3 { get; set; }
    }
}
