//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_1.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCIResponseTicket
    {
        public Nullable<int> TicketId { get; set; }
        public string ExternalReferenceNo { get; set; }
        public string CompanyName { get; set; }
        public string FullName { get; set; }
        public string LocationName { get; set; }
        public string StatusName { get; set; }
        public string PriorityName { get; set; }
        public string AssigneeName { get; set; }
        public string ApplicationName { get; set; }
        public Nullable<bool> IsMajorIncident { get; set; }
        public string Description { get; set; }
        public string RootCause { get; set; }
        public string Resolution { get; set; }
        public string Notes { get; set; }
        public string EscalationGroupName { get; set; }
        public string SourceName { get; set; }
        public string ReportedDate { get; set; }
        public string ResolvedDate { get; set; }
        public string CreationDate { get; set; }
        public string LastModificationDate { get; set; }
        public string RootCause_Lv1_Category { get; set; }
        public string RootCause_Lv2_Category { get; set; }
        public string RootCause_Lv3_Category { get; set; }
        public string ReportedIssue_Lv1_Category { get; set; }
        public string ReportedIssue_Lv2_Category { get; set; }
        public string ReportedIssue_Lv3_Category { get; set; }
        public string Action1__Lv1_Category { get; set; }
        public string Action1__Lv2_Category { get; set; }
        public string Action1__Lv3_Category { get; set; }
        public string Action2__Lv1_Category { get; set; }
        public string Action2__Lv2_Category { get; set; }
        public string Action2__Lv3_Category { get; set; }
        public string Action3__Lv1_Category { get; set; }
        public string Action3__Lv2_Category { get; set; }
        public string Action3__Lv3_Category { get; set; }
        public string Production_Unit_Name { get; set; }
    }
}
