//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_1.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public string ExternalReferenceNo { get; set; }
        public int CompanyId { get; set; }
        public int ContactId { get; set; }
        public int LocationId { get; set; }
        public int StatusId { get; set; }
        public int PriorityId { get; set; }
        public int AssigneeId { get; set; }
        public int ApplicationId { get; set; }
        public bool IsMajorIncident { get; set; }
        public string Description { get; set; }
        public string RootCause { get; set; }
        public string Resolution { get; set; }
        public string Notes { get; set; }
        public Nullable<int> EscalationGroupId { get; set; }
        public int SourceId { get; set; }
        public System.DateTime ReportedDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModificationDate { get; set; }
        public Nullable<int> RootCause_Tree_DataId { get; set; }
        public Nullable<int> ReportedIssue_Tree_DataId { get; set; }
        public Nullable<int> Action1_Tree_DataId { get; set; }
        public Nullable<int> Action2_Tree_DataId { get; set; }
        public Nullable<int> Action3_Tree_DataId { get; set; }
        public Nullable<int> ProductionUnitId { get; set; }
    
        public virtual Action_Tree_Data Action_Tree_Data { get; set; }
        public virtual Action_Tree_Data Action_Tree_Data1 { get; set; }
        public virtual Action_Tree_Data Action_Tree_Data2 { get; set; }
        public virtual Application Application { get; set; }
        public virtual Assignee Assignee { get; set; }
        public virtual Company Company { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual EscalationGroup EscalationGroup { get; set; }
        public virtual Location Location { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual ProductionUnit ProductionUnit { get; set; }
        public virtual ReportedIssue_Tree_Data ReportedIssue_Tree_Data { get; set; }
        public virtual RootCause_Tree_Data RootCause_Tree_Data { get; set; }
        public virtual Source Source { get; set; }
        public virtual Status Status { get; set; }
    }
}
