//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWork_1.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCIEntities : DbContext
    {
        public PCIEntities()
            : base("name=PCIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_Tree_Data> Action_Tree_Data { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Assignee> Assignees { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<EscalationGroup> EscalationGroups { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<ProductionLine> ProductionLines { get; set; }
        public virtual DbSet<ProductionUnit> ProductionUnits { get; set; }
        public virtual DbSet<ReportedIssue_Tree_Data> ReportedIssue_Tree_Data { get; set; }
        public virtual DbSet<RootCause_Tree_Data> RootCause_Tree_Data { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<UnitDowntime> UnitDowntimes { get; set; }
        public virtual DbSet<PCIResponseTicket> PCIResponseTickets { get; set; }
        public virtual DbSet<PCIResponseTicketsReport> PCIResponseTicketsReports { get; set; }
    }
}
